<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce - Login to admin</title>
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('font/bootstrap-icons.css') }}">
    <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
    <style>
        /* Background styles */
        body {
            background-color: #364571;

        }

        /* Glassmorphism card effect */
        .card {
            backdrop-filter: blur(16px) saturate(180%);
            -webkit-backdrop-filter: blur(16px) saturate(180%);
            background-color: rgba(6, 22, 58, 0.75);
            border-radius: 12px;
            border: 1px solid rgba(209, 213, 219, 0.3);
            margin-top: 30%;


        }

        /* Generated by https://generator.ui.glass/ */
    </style>
</head>

<body>
    <div class="container">
        <div class=" col-md-4 offset-md-4 ">

            <form action=" {{ route('auth') }}" method="post" style="margin-top: 25px;" class="card card-body shadow">
                @csrf
                <center>
                    <i class="bi bi-person-circle text-white" style="font-size: 90px;"></i>
                </center>
                @error('errorTitle')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <h1 class="text-white">Login</h1>
                <p class="text-light">Login to access your account.</p>
                <div class="mb-2">
                    <label for="email" class="text-white">Username</label>
                    <input type="text" name="email" id="email" value="{{ old('email') }}"
                        class="form-control @error('email') is-invalid @enderror" placeholder="Username" autofocus>
                </div>
                <div class="mb-2">
                    <label for="password" class="text-white">Password</label>
                    <input type="password" name="password" id="password"
                        class="form-control @error('password') is-invalid @enderror" placeholder="Password"
                        value="{{ old('password') }}">
                </div>
                <div class="d-grid gap-2 mt-3">
                    <button class="btn btn-lg btn-outline-light mb-3" type="submit" name="submit">Login</button>
                </div>
                <!-- <div class="alert alert-primary d-flex align-items-center mt-3" role="alert">
                    <i class="bi bi-info-circle-fill"></i>&nbsp;
                    <strong>Expired!</strong>&nbsp;<span> Software will be expire soon.</span>
                </div> -->
            </form>
        </div>
    </div>
</body>

</html>
